package com.sevenyes.mysportteams.events.domain.models


data class DomainEvent(
    val dateEvent: String = "",
    val dateEventLocal: String = "",
    val idAwayTeam: String = "",
    val idEvent: String = "",
    val idHomeTeam: String = "",
    val idLeague: String = "",
    val intAwayScore: String = "",
    val intHomeScore: String = "",
    val intRound: String = "",
    val strAwayTeam: String = "",
    val strBanner: String = "",
    val strCity: String = "",
    val strCountry: String = "",
    val strDescriptionEN: String = "",
    val strEvent: String = "",
    val strEventAlternate: String = "",
    val strFilename: String = "",
    val strHomeTeam: String = "",
    val strLeague: String = "",
    val strLocked: String = "",
    val strPoster: String = "",
    val strPostponed: String = "",
    val strResult: String = "",
    val strSeason: String = "",
    val strSport: String = "",
    val strSquare: String = "",
    val strStatus: String = "",
    val strThumb: String = "",
    val strTime: String = "",
    val strTimeLocal: String = "",
    val strTimestamp: String = "",
    val strTweet1: String = "",
    val strTweet2: String = "",
    val strTweet3: String = "",
    val strVenue: String = "",
    val strVideo: String = ""
)